### ISSUE TITLE
非常好的项目,提两个建议

### ISSUE THREAD

**Issue by ghost** [wenjiax/stress#1]
1.增加Proxy;
压力测试也可以是远程测试,很多时候需要用到proxy.

2.增加每个生命周期上下文管理;
因为支持多个站点一起测试,所以需要可以暂停其中测试其中某个站点而不影响其他测试.

**Comment by wenjiax** [comment]
感谢建议,之后会完善.

**Comment by wenjiax** [comment]
@gofmt 
f9b1628271c40fdcfb93b8356fbf6be4fa7cecb8
1. 增加Proxy.
2. 增加ThinkTime.
